const male = require('./../../assets/icon__male.png');
const female = require('./../../assets/icon__female.png');
export const pets = [
    {
        id:1,
        name: 'Biszkopt',
        gender: male,
        age: '4 miesięce',
        agePet: 'kitty',
        likeOtherPet: true,
        castrated: true,
        dateofbirth: '12-01-2020',
        hair: 'medium breast',
        healthyComment: 'not healthy problems',
        color: 'red',
        sibilings: true,
        purebread: true,
        social: true,
        overview: 'Lorem ipsum dolor sit amet, cons ectetur adipiscing elit, quis ipsum suspen disse ultrices',
        source: require('./../../assets/IMG_2847.jpeg'),
    },
    {
        id:2,
        name: 'Grześ',
        gender: male,
        age: '6 miesięcy',
        agePet: 'adult',
        likeOtherPet: false,
        castrated: true,
        dateofbirth: '12-01-2020',
        hair: 'short',
        healthyComment: 'not healthy problems',
        color: 'red',
        sibilings: true,
        purebread: true,
        social: true,
        overview: 'Lorem ipsum dolor sit amet, cons ectetur adipiscing elit, quis ipsum suspen disse ultrices',
        source: require('./../../assets/IMG_3291.jpeg'),
    },
    {
        id:3,
        name: 'Nairobi',
        gender: female,
        age: '2 lata',
        agePet: 'kitty',
        likeOtherPet: true,
        castrated: false,
        dateofbirth: '12-01-2020',
        hair: 'short',
        healthyComment: 'not healthy problems',
        color: 'red',
        sibilings: true,
        purebread: true,
        social: true,
        overview: 'Lorem ipsum dolor sit amet, cons ectetur adipiscing elit, quis ipsum suspen disse ultrices',
        source: require('./../../assets/IMG_4100.jpeg'),
    },
    {
        id:4,
        name: 'Igor',
        gender: male,
        age: '2,5 roku',
        agePet: 'adult',
        likeOtherPet: true,
        castrated: true,
        dateofbirth: '12-01-2020',
        hair: 'short',
        healthyComment: 'not healthy problems',
        color: 'red',
        sibilings: false,
        purebread: true,
        social: true,
        overview: 'Lorem ipsum dolor sit amet, cons ectetur adipiscing elit, quis ipsum suspen disse ultrices',
        source: require('./../../assets/IMG_7652.jpeg'),
    },
    {
        id:5,
        name: 'Eliza',
        gender: female,
        age: '3 lata',
        agePet: 'senior',
        likeOtherPet: true,
        castrated: true,
        dateofbirth: '12-01-2020',
        hair: 'long',
        healthyComment: 'not healthy problems',
        color: 'red',
        sibilings: false,
        purebread: true,
        social: true,
        overview: 'Lorem ipsum dolor sit amet, cons ectetur adipiscing elit, quis ipsum suspen disse ultrices',
        source: require('./../../assets/eliza.jpeg'),
    },
    {
        id:6,
        name: 'Simba',
        gender: male,
        age: '9 miesięcy',
        agePet: 'adult',
        likeOtherPet: false,
        castrated: false,
        dateofbirth: '12-01-2020',
        hair: 'short',
        healthyComment: 'not healthy problems',
        color: 'red',
        sibilings: false,
        purebread: true,
        social: false,
        overview: 'Lorem ipsum dolor sit amet, cons ectetur adipiscing elit, quis ipsum suspen disse ultrices',
        source: require('./../../assets/simba.jpeg'),
    },
    {
        id:7,
        name: 'Wampirek',
        gender: male,
        age: '1 rok',
        agePet: 'adult',
        likeOtherPet: false,
        castrated: false,
        dateofbirth: '12-01-2020',
        hair: 'short',
        healthyComment: 'not healthy problems',
        color: 'red',
        sibilings: false,
        purebread: true,
        social: false,
        overview: 'Lorem ipsum dolor sit amet, cons ectetur adipiscing elit, quis ipsum suspend isse ultrices',
        source: require('./../../assets/wampir.jpeg'),
    }
]